builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: cmd/helm-values-manager/main.go
    binary: helm-values-manager
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: helm-values-manager
    tap:
      owner: xunholy
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/xunholy/helm-values-manager"
    description: "A Helm plugin to analyze, optimize, and clean Helm values.yaml files"
    license: "Apache-2.0"
    install: |
      bin.install "helm-values-manager"

dockers:
  - image_templates:
      - "ghcr.io/xunholy/helm-values-manager:{{ .Version }}"
      - "ghcr.io/xunholy/helm-values-manager:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
