additionalContainers: {}
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
container:
  image:
    pullPolicy: IfNotPresent
    repository: xunholy/example-1
    tag: sha-e307597
fullnameOverride: ""
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
initContainer:
  image:
    pullPolicy: IfNotPresent
    repository: willdockerhub/git-sync
    tag: v3.3.5
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 3
